=== Hermain54/WSD_Test/struct.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Company">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="Employee">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Emp-name" type="xs:string"/>
            <xs:element name="Emp-age" type="xs:decimal"/>
            <xs:element name="Emp-salary" type="mySalary"/>
            <xs:element name="Emp-emailid" type="xs:string"/>
            <xs:element name="Emp-Phonenum" type="xs:positiveInteger" />
            <xs:element name="Emp-Designation" type="xs:string"/>
          </xs:sequence>
         <xs:attribute name="Emp-id" type="xs:ID" use="required" /> 
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:simpleType name="mySalary">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="50000"/>
    <xs:maxInclusive value="200000"/>
  </xs:restriction>
</xs:simpleType>
</xs:schema>

=== Hermain54/WSD_Test/info.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="struct.xsd">
<Employee>
<Emp-id>1001</Emp-id>
<Emp-name>Aamina</Emp-name>
<Emp-age>25</Emp-age>
<Emp-salary>65000</Emp-salary>
<Emp-emailid>aamina@gmail.com</Emp-emailid>
<Emp-Phonenum>9988556633</Emp-Phonenum>
<Emp-Designation>Supervisor</Emp-Designation>
</Employee>
<Employee>
<Emp-id>1002</Emp-id>
<Emp-name>Daniel</Emp-name>
<Emp-age>40</Emp-age>
<Emp-salary>85000</Emp-salary>
<Emp-emailid>daniel@gmail.com</Emp-emailid>
<Emp-Phonenum>9778855433</Emp-Phonenum>
<Emp-Designation>Associate-Employee</Emp-Designation>
</Employee>
<Employee>
<Emp-id>1003</Emp-id>
<Emp-name>Shareha</Emp-name>
<Emp-age>35</Emp-age>
<Emp-salary>76000</Emp-salary>
<Emp-emailid>shareha@gmail.com</Emp-emailid>
<Emp-Phonenum>9890637300</Emp-Phonenum>
<Emp-Designation>Associate-Employee</Emp-Designation>
</Employee>
<Employee>
<Emp-id>1004</Emp-id>
<Emp-name>Shaila</Emp-name>
<Emp-age>22</Emp-age>
<Emp-salary>85000</Emp-salary>
<Emp-emailid>shaila@gmail.com</Emp-emailid>
<Emp-Phonenum>9678892338</Emp-Phonenum>
<Emp-Designation>Associate-Employee</Emp-Designation>
</Employee>
<Employee>
<Emp-id>1005</Emp-id>
<Emp-name>Shamak</Emp-name>
<Emp-age>50</Emp-age>
<Emp-salary>95000</Emp-salary>
<Emp-emailid>shamak@gmail.com</Emp-emailid>
<Emp-Phonenum>9763128964</Emp-Phonenum>
<Emp-Designation>Manager</Emp-Designation>
</Employee>
<Employee>
<Emp-id>1006</Emp-id>
<Emp-name>Farheen</Emp-name>
<Emp-age>60</Emp-age>
<Emp-salary>85000</Emp-salary>
<Emp-emailid>farheen@gmail.com</Emp-emailid>
<Emp-Phonenum>9865446033</Emp-Phonenum>
<Emp-Designation>Associate-Employee</Emp-Designation>
</Employee>
<Employee>
<Emp-id>1007</Emp-id>
<Emp-name>Shaheen</Emp-name>
<Emp-age>29</Emp-age>
<Emp-salary>83000</Emp-salary>
<Emp-emailid>shaheen@gmail.com</Emp-emailid>
<Emp-Phonenum>7854146033</Emp-Phonenum>
<Emp-Designation>Associate-Employee</Emp-Designation>
</Employee>
</Company>
